#!/usr/bin/env python3
"""Generate the delivery documents from workflow-plan.json; --check refuses drift."""
from pathlib import Path
import argparse,json,hashlib
B=Path(__file__).resolve().parents[1]
EXPECTED='P0 B1 C1 M1 W1 B2 M2 M3 J1 W2 W3 W4 W5 X1 A1 R1 R2 R3 I1 D1 D2 P1 V1 U1 W6 W7 X2 X3 X4 X5 C2 R3B C2S'.split()
RULES=[f'EP{i:02d}' for i in range(1,14)]
NAMES=['Ship-Verified-SupraOS-Agent-Workflows.md','SupraOS-Workflow-Plan-Checklist.md','Delivery-Path-Release-Plan.md','Evidence-Index.md']
def render(d):
 assert [t['id'] for t in d['tasks']]==EXPECTED,'33 task identities/order must remain'
 assert [x['id'] for x in d['principles']]==RULES,'Permanent execution principles missing'
 assert len(d['scope']['behaviors'])==16 and len(d['scope']['surfaces'])==12
 assert d['scope']['deferred']==['iMessage'] and d['scope']['excluded']==['WhatsApp']
 assert all(t['acceptance'] and t['source'] and t['remaining'] and t['baselineRecord']['id']==t['id'] for t in d['tasks'])
 ids=set(EXPECTED)
 assert all(set(t['originalDependencies'])<=ids for t in d['tasks'])
 graph=d['deliveryGraph'];g={x['id']:x for x in graph};assert len(g)==len(graph)
 remaining=set(g);done=set();rounds=[]
 while remaining:
  ready=[x['id'] for x in graph if x['id'] in remaining and set(x['blockedBy'])<=done]
  assert ready,'Dependency cycle or missing ID';rounds.append(ready);done.update(ready);remaining-=set(ready)
 for s in graph:
  assert all(s[k] for k in ['owner','makesTrue','acceptance','taskIds','ownedFiles','blockerKind'])
 digest=hashlib.sha256((B/'workflow-plan.json').read_bytes()).hexdigest()
 nav='[Handoff](Ship-Verified-SupraOS-Agent-Workflows.md) · [Checklist](SupraOS-Workflow-Plan-Checklist.md) · [Dependency plan](Delivery-Path-Release-Plan.md) · [Evidence index](Evidence-Index.md) · [Canonical record](workflow-plan.json) · [Repository instructions](AGENTS.md)'
 head=f'''{nav}

Delivery strategy revision: **{d['updatedAt']}**. Canonical record SHA-256: `{digest}`.

**Execution state:** {d['executionState']}.

**Scope:** all 33 tasks, 16 behavior families and 12 supported surfaces remain required. W7 is an intermediate milestone. iMessage is deferred; WhatsApp is excluded.

**Current delivery checkpoint:** {d.get('activeCheckpoint', 'See current task contracts below.')}

**Current candidate record:** `{d['candidateSummary']['commit']}`, tree `{d['candidateSummary']['tree']}`. Security: {d['candidateSummary']['requiredSecurity']}; build: {d['candidateSummary']['requiredBuild']}; macOS Native Land: {d['candidateSummary']['nativeLand']}. Merged: {d['candidateSummary']['merged']}; deployed: {d['candidateSummary']['deployed']}; activated: {d['candidateSummary']['activated']}; verified live: {d['candidateSummary']['verifiedLive']}. Scope: {d['candidateSummary']['scope']}. Observed: {d['candidateSummary']['observedAt']}. Update this canonical candidate record after changes; never infer status from historical receipts.

**Dated recovery baseline:** strict E3 was RED with 6,540 blockers at the prior closeout. These observations are not permission to skip fresh release checks.

Private portable evidence: `04795ddf0c18af8d40960ea29993fbf93535f5de` (2,291 restored files / 957 objects / 1,036 remotely verified transport files). Archive predates final CI; retain its original state. Baseline public handoff: `{d['baselinePublicCommit']}`. Historical documents are preserved under [history](history/20261005-before-delivery-rewrite/); historical statuses are not current authority.
'''
 head+='\n\n'+d.get('pauseHandoff','')+'\n\n'+d.get('pauseEvidenceRecovery','')+'\n'
 rules='## Permanent execution principles\n\nThese rules must remain in every future handoff, checklist and plan. Update their canonical entries rather than deleting them during a status refresh.\n\n'+'\n\n'.join(f"**{p['id']} — {p['title']}.** {p['rule']}" for p in d['principles'])
 maintain='''## Updating and handing off this plan

1. Read this revision, the canonical record and product repository instructions before starting. Inspect existing code and receipts; distinguish missing code from missing proof/access.
2. Update `workflow-plan.json`: current evidence, task stages, actual blocker, named owner, next proof, exact candidate and timestamps. Retain historical baseline records and all task acceptance criteria.
3. Run `python3 scripts/render_plan.py`, then `python3 scripts/render_plan.py --check`. The check verifies scope, policy IDs, an acyclic graph and exact generated bytes. It does not verify product behavior.
4. Publish the record and generated files in one reviewed commit. Secret-scan plaintext before uploading evidence; encoding is not sanitization. Reuse the existing hash-manifest packaging and independent reconstruction checks.
5. Verify remote bytes and anonymous browser rendering for the three entry documents, all 33 checklist rows and the dependency graph. Record the publication/browser receipt separately; avoid a self-referential commit-hash rewrite loop.

Checkpoint report: **usable capability advanced; dependency closed; exact blocker and category; accountable owner; proof needed; next action; source/test/review/merge/deploy/activation/live state; elapsed delivery time**. Unknown timestamps remain unknown. Publish on meaningful dependency closure, blocker change, pause or handoff—not after every tool call.

The generator catches missing rules and stale generated views when run. `AGENTS.md` instructs future agents to run it; no runtime enforcement in SupraOS Build or mandatory GitHub branch protection has been installed by this documentation change.
'''
 table='## Current full-scope checklist — all 33 tracked items\n\n| ID / work | Evidence state | Remaining work |\n| --- | --- | --- |\n'+'\n'.join(f"| **{t['id']} — {t['title']}** | {t['savedWork'].replace('|','/')} | {t['remaining'].replace('|','/')} |" for t in d['tasks'])
 reuse='## Reuse before writing code\n\nMissing deployment or live evidence does not mean the implementation is absent. Verify source and authority before extending these assets.\n\n| Existing component | Source / location | Proven scope | What NOT to rebuild |\n| --- | --- | --- | --- |\n'+'\n'.join(f"| {r['component']} | `{r['source']}`; `{r['location']}` | {r['evidence']} | {r['instruction']} |" for r in d['reuseInventory'])
 lanes='''## Parallel lanes and work limits

| Lane | Accountable work | May run now / after resume | Ownership boundary |
| --- | --- | --- | --- |
| Root | Scope, candidate, integration decisions, documentation and release coordination | Verify exact baseline and assign owners; resolve blockers | Does not silently replace another lane's source |
| Implementation | Failure drain, real automated/manual callers, recovery and truthful parent receipts | First implementation priority; one shared-file owner | Orchestrator, transition helpers and additive authority SQL owned together |
| Prerequisites | Writer/accepted-work controls, schema/roles, restoration, normal QA/provider access | In parallel from the first round | Own release packets and access records; coordinate shared source changes |
| Independent verification | Red regression, cheap preflight, source review, SQL/REST and applicable browser checks | Prepare alongside implementation; qualify immutable source afterward | No concurrent edits to implementation files; preserve failed evidence |

Start with root plus these three lanes where capacity permits. More agents get bounded independent subtasks only when they remove a dependency; they do not create extra feature streams. Grok can trace code/design tests or audit when its connector permits; read-only output is not an implementation. If a requested model is unavailable, disclose and record the fallback or capacity blocker.

Rounds below show dependency eligibility, not unlimited concurrency or duration estimates. Reconcile file ownership, CPU/memory/native host limits and access before dispatch. Keep one high-impact code slice in progress; finish failure drain before opening the next effect. BROADER is a preserved backlog umbrella, not permission to start all its tasks at once.
'''
 dag='## Parallel ownership and dependency graph\n\n```mermaid\nflowchart TD\n'
 for s in graph:dag+=f'  {s["id"]}["{s["makesTrue"]}"]\n'
 for s in graph:
  for x in s['blockedBy']:dag+=f'  {x} --> {s["id"]}\n'
 dag+='```\n\n'
 dag+='| Step | Depends on | Owner | Makes true / acceptance | Task coverage / owned files | Blocker category |\n| --- | --- | --- | --- | --- | --- |\n'
 for s in graph:dag+=f"| {s['id']} | {', '.join(s['blockedBy']) or 'None'} | {s['owner']} | {s['makesTrue']}: {s['acceptance']} | {s['taskIds']}; {s['ownedFiles']} | {s['blockerKind']} |\n"
 dag+='\nDependency rounds: '+ '; '.join(f"{i+1}: {', '.join(r)}" for i,r in enumerate(rounds))+'.\n\nThe longest edge-count path is not an effort estimate. Release prerequisites can dominate elapsed time despite a shorter graph path. W7 may ship as a separately qualified milestone only with an explicit release manifest and its required gates; full project completion still requires every task/behavior/surface.\n'
 contracts='## Detailed task contracts and preserved evidence\n\nHistorical baseline implementation/evidence is retained verbatim in `workflow-plan.json` under each task’s `baselineRecord`. It may predate the current saved-work summary. Original dependency IDs are retained below; dispatch dependencies above are the revised execution sequence. An empty original dependency list does not waive release prerequisites.\n'
 for t in d['tasks']:
  contracts+=f"\n### {t['id']} — {t['title']}\n\n**Saved work:** {t['savedWork']}\n\n**Remaining:** {t['remaining']}\n\n**Acceptance:** {t['acceptance']}\n\n**Source:** {t['source']}\n\n**Prior owner role:** {t['ownerRole']}. Root must assign a currently available named owner before dispatch. **Original dependencies:** {', '.join(t['originalDependencies']) or 'None recorded'}.\n\n| Stage | Current evidence boundary |\n| --- | --- |\n"
  contracts+='\n'.join(f'| {k} | {v} |' for k,v in t['stages'].items())+'\n'
 behavior='## Full behavior and surface acceptance\n\n'+ '\n'.join(f"- **{x['id']}** {x['title']} — {x['status']}" for x in d['scope']['behaviors'])+'\n\nSupported surfaces:\n\n'+ '\n'.join(f'{i+1}. {x}' for i,x in enumerate(d['scope']['surfaces']))
 prereq='''## Release feasibility and external requests

| Dependency | Owner role | Exact request / proof | Work that continues meanwhile |
| --- | --- | --- | --- |
| Production writer and accepted-work control | Authorized release operator | Supported mechanism and target-bound inventory covering every writer, pending/active/unknown work and old broadcasters; faithful current-target restore evidence | Read code, prepare guarded packets and private rehearsals |
| Schema and runtime roles | Release/database operator | Fresh ledger/schema/function/ACL/pooler inventory; ordered forward/VERIFY/rollback compatibility | Compare already prepared packets; do not replay installed migrations |
| Normal authenticated QA | Existing member/account owner | Normal invite and owner/foreign-owner QA sessions; no credentials in handoff and no invite bypass | Synthetic/native negative tests and public browser checks |
| Stripe Link/provider/computer | Provider/account owner | Issued configuration status and normal approved setup/inputs | Reversible adapter tests; no unsolicited real effects |

These are outstanding categories, not claims that a new request has been sent. Inspect the prior request history before contacting anyone. Send messages only under the user's existing explicit authorization or a fresh applicable instruction. A release-feasibility finding should identify code, evidence, access or approval precisely; do not label unfinished code as an external blocker.
'''
 gaps='''## Remaining effects after the drain

Preserve this inventory until each destination has its original identity, actual caller, integration owner and acceptance receipt: manual terminal events and retrospective parity; Hindsight original action/outcome; analyzer output and report memory/provenance; broadcast provenance; legitimate caller-saved department recipients; completion/failure umbrella broadcasts and legacy terminal fallback; safe active cancellation; real L1 execution. Existing notification/estimation/retro slices must be extended or qualified, not rebuilt. Planner assignments do not establish recipient consent. Unknown work remains held; do not manufacture terminality to deliver a notification.
'''
 evidence='## Evidence reuse and qualification ladder\n\n'+d['evidenceQuality']+'''

For each receipt record: exact source commit/tree and imported-file hashes; schema/role/config/runtime fingerprints; test command/version and input identity; positive/negative/recovery scope; outcome and failed evidence; cleanup; independent reviewer; invalidating changes. Mark reuse as scoped parity, never a new execution.

Run in this order when applicable: source/caller inspection → focused regression/types/fixture checks → SQL parse/load and no-host checks → bounded native SQL/REST → independent actual caller and browser review → required exact-source CI → guarded rollout → authenticated live acceptance and tested recovery. Setup failure is not product failure; preserve and diagnose it without weakening budgets. A passing lower step does not substitute for a higher one.

The existing manifests and private packet are the starting point. Consolidation means parameterizing proven harness components during needed work; it is not a separate harness rewrite project. Keep native runs within existing resource controls and distinct owned scratch. Preserve one-use attempt semantics.
'''
 metrics='## Delivery metrics\n\n```json\n'+json.dumps(d['metrics'],indent=2)+'\n```\n\nRecord useful delivery milestones and wait categories. Compare actual elapsed times after enough data exists; do not promise speedup percentages from agent count.\n'
 handoff='# Ship Verified SupraOS Agent Workflows\n\n'+head+'\n## Goals and current result\n\n'+d['currentAccomplishments']+'\n\n## Already shipped versus pending\n\n'+d['shippedScope']+'\n\n'+rules+'\n\n'+reuse+'\n\n'+lanes+'\n\n## Preserved failure-drain design analysis\n\n'+d['drainContract']+'\n\n'+gaps+'\n\n'+prereq+'\n\n## Code locations and fresh-computer recovery\n\n'+d['sourceAndRecovery']+'\n\n'+behavior+'\n\n## Definition of finished\n\n'+d['definitionFinished']+'\n\n'+maintain
 checklist='# SupraOS Release Plan Checklist\n\n'+head+'\n'+rules+'\n\n'+table+'\n\n'+contracts+'\n\n'+behavior+'\n\n'+maintain
 plan='# Ship Verified System Workflow Outcomes\n\n'+head+'\n'+rules+'\n\n'+lanes+'\n\n'+dag+'\n\n'+reuse+'\n\n## Preserved failure-drain design contract\n\n'+d['drainContract']+'\n\n'+gaps+'\n\n'+prereq+'\n\n'+evidence+'\n\n'+metrics+'\n\n## Full scope preservation\n\nThe [33-task checklist](SupraOS-Workflow-Plan-Checklist.md) carries every acceptance contract, source pointer and original dependency. The canonical record also preserves all 20 previous release slices and 16 prior delivery steps, labeled historical. Do not execute outdated slice states without current reconciliation.\n\n'+maintain
 index='# SupraOS Workflow Evidence Index\n\n'+head+'\n'+reuse+'\n\n'+evidence+'\n\n## Recovery and source locations\n\n'+d['sourceAndRecovery']+'\n\n'+maintain
 return dict(zip(NAMES,[handoff,checklist,plan,index]))
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args();d=json.loads((B/'workflow-plan.json').read_text());docs=render(d)
 for name,text in docs.items():
  if a.check:assert (B/name).read_text()==text,'Stale generated document: '+name
  else:(B/name).write_text(text)
 print(json.dumps({'mode':'check' if a.check else 'render','documents':len(docs),'tasks':33,'rules':13,'behaviors':16,'surfaces':12,'verdict':'PASS'}))
